// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/response.proto

package protos;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeersListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PeersList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    java.util.List<protos.Node.NodeDetails> 
        getNodesList();
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    protos.Node.NodeDetails getNodes(int index);
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    java.util.List<? extends protos.Node.NodeDetailsOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    protos.Node.NodeDetailsOrBuilder getNodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PeersList}
   */
  public static final class PeersList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PeersList)
      PeersListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PeersList.newBuilder() to construct.
    private PeersList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PeersList() {
      nodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PeersList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PeersList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodes_ = new java.util.ArrayList<protos.Node.NodeDetails>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodes_.add(
                  input.readMessage(protos.Node.NodeDetails.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Response.internal_static_PeersList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Response.internal_static_PeersList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Response.PeersList.class, protos.Response.PeersList.Builder.class);
    }

    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<protos.Node.NodeDetails> nodes_;
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<protos.Node.NodeDetails> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protos.Node.NodeDetailsOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    @java.lang.Override
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    @java.lang.Override
    public protos.Node.NodeDetails getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .NodeDetails nodes = 1;</code>
     */
    @java.lang.Override
    public protos.Node.NodeDetailsOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Response.PeersList)) {
        return super.equals(obj);
      }
      protos.Response.PeersList other = (protos.Response.PeersList) obj;

      if (!getNodesList()
          .equals(other.getNodesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Response.PeersList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.PeersList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.PeersList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.PeersList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.PeersList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.PeersList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.PeersList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Response.PeersList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Response.PeersList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Response.PeersList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Response.PeersList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Response.PeersList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Response.PeersList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PeersList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PeersList)
        protos.Response.PeersListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Response.internal_static_PeersList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Response.internal_static_PeersList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Response.PeersList.class, protos.Response.PeersList.Builder.class);
      }

      // Construct using protos.Response.PeersList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Response.internal_static_PeersList_descriptor;
      }

      @java.lang.Override
      public protos.Response.PeersList getDefaultInstanceForType() {
        return protos.Response.PeersList.getDefaultInstance();
      }

      @java.lang.Override
      public protos.Response.PeersList build() {
        protos.Response.PeersList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.Response.PeersList buildPartial() {
        protos.Response.PeersList result = new protos.Response.PeersList(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Response.PeersList) {
          return mergeFrom((protos.Response.PeersList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Response.PeersList other) {
        if (other == protos.Response.PeersList.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Response.PeersList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Response.PeersList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.Node.NodeDetails> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodes_ = new java.util.ArrayList<protos.Node.NodeDetails>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.Node.NodeDetails, protos.Node.NodeDetails.Builder, protos.Node.NodeDetailsOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public java.util.List<protos.Node.NodeDetails> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public protos.Node.NodeDetails getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder setNodes(
          int index, protos.Node.NodeDetails value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder setNodes(
          int index, protos.Node.NodeDetails.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder addNodes(protos.Node.NodeDetails value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder addNodes(
          int index, protos.Node.NodeDetails value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder addNodes(
          protos.Node.NodeDetails.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder addNodes(
          int index, protos.Node.NodeDetails.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends protos.Node.NodeDetails> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public protos.Node.NodeDetails.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public protos.Node.NodeDetailsOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public java.util.List<? extends protos.Node.NodeDetailsOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public protos.Node.NodeDetails.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            protos.Node.NodeDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public protos.Node.NodeDetails.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, protos.Node.NodeDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeDetails nodes = 1;</code>
       */
      public java.util.List<protos.Node.NodeDetails.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.Node.NodeDetails, protos.Node.NodeDetails.Builder, protos.Node.NodeDetailsOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protos.Node.NodeDetails, protos.Node.NodeDetails.Builder, protos.Node.NodeDetailsOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PeersList)
    }

    // @@protoc_insertion_point(class_scope:PeersList)
    private static final protos.Response.PeersList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Response.PeersList();
    }

    public static protos.Response.PeersList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PeersList>
        PARSER = new com.google.protobuf.AbstractParser<PeersList>() {
      @java.lang.Override
      public PeersList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeersList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PeersList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeersList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.Response.PeersList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */
    int getPiecesInfoCount();
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */
    boolean containsPiecesInfo(
        long key);
    /**
     * Use {@link #getPiecesInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, protos.Response.PeersList>
    getPiecesInfo();
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */
    java.util.Map<java.lang.Long, protos.Response.PeersList>
    getPiecesInfoMap();
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */

    protos.Response.PeersList getPiecesInfoOrDefault(
        long key,
        protos.Response.PeersList defaultValue);
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */

    protos.Response.PeersList getPiecesInfoOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code FileInfo}
   */
  public static final class FileInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileInfo)
      FileInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileInfo.newBuilder() to construct.
    private FileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                piecesInfo_ = com.google.protobuf.MapField.newMapField(
                    PiecesInfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Long, protos.Response.PeersList>
              piecesInfo__ = input.readMessage(
                  PiecesInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              piecesInfo_.getMutableMap().put(
                  piecesInfo__.getKey(), piecesInfo__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Response.internal_static_FileInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetPiecesInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Response.internal_static_FileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Response.FileInfo.class, protos.Response.FileInfo.Builder.class);
    }

    public static final int PIECESINFO_FIELD_NUMBER = 1;
    private static final class PiecesInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, protos.Response.PeersList> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, protos.Response.PeersList>newDefaultInstance(
                  protos.Response.internal_static_FileInfo_PiecesInfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protos.Response.PeersList.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Long, protos.Response.PeersList> piecesInfo_;
    private com.google.protobuf.MapField<java.lang.Long, protos.Response.PeersList>
    internalGetPiecesInfo() {
      if (piecesInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PiecesInfoDefaultEntryHolder.defaultEntry);
      }
      return piecesInfo_;
    }

    public int getPiecesInfoCount() {
      return internalGetPiecesInfo().getMap().size();
    }
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */

    @java.lang.Override
    public boolean containsPiecesInfo(
        long key) {
      
      return internalGetPiecesInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPiecesInfoMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, protos.Response.PeersList> getPiecesInfo() {
      return getPiecesInfoMap();
    }
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, protos.Response.PeersList> getPiecesInfoMap() {
      return internalGetPiecesInfo().getMap();
    }
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */
    @java.lang.Override

    public protos.Response.PeersList getPiecesInfoOrDefault(
        long key,
        protos.Response.PeersList defaultValue) {
      
      java.util.Map<java.lang.Long, protos.Response.PeersList> map =
          internalGetPiecesInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
     */
    @java.lang.Override

    public protos.Response.PeersList getPiecesInfoOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, protos.Response.PeersList> map =
          internalGetPiecesInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetPiecesInfo(),
          PiecesInfoDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Long, protos.Response.PeersList> entry
           : internalGetPiecesInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, protos.Response.PeersList>
        piecesInfo__ = PiecesInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, piecesInfo__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Response.FileInfo)) {
        return super.equals(obj);
      }
      protos.Response.FileInfo other = (protos.Response.FileInfo) obj;

      if (!internalGetPiecesInfo().equals(
          other.internalGetPiecesInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetPiecesInfo().getMap().isEmpty()) {
        hash = (37 * hash) + PIECESINFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPiecesInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Response.FileInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.FileInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.FileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.FileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.FileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.FileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.FileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Response.FileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Response.FileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Response.FileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Response.FileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Response.FileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Response.FileInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileInfo)
        protos.Response.FileInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Response.internal_static_FileInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetPiecesInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutablePiecesInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Response.internal_static_FileInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Response.FileInfo.class, protos.Response.FileInfo.Builder.class);
      }

      // Construct using protos.Response.FileInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutablePiecesInfo().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Response.internal_static_FileInfo_descriptor;
      }

      @java.lang.Override
      public protos.Response.FileInfo getDefaultInstanceForType() {
        return protos.Response.FileInfo.getDefaultInstance();
      }

      @java.lang.Override
      public protos.Response.FileInfo build() {
        protos.Response.FileInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.Response.FileInfo buildPartial() {
        protos.Response.FileInfo result = new protos.Response.FileInfo(this);
        int from_bitField0_ = bitField0_;
        result.piecesInfo_ = internalGetPiecesInfo();
        result.piecesInfo_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Response.FileInfo) {
          return mergeFrom((protos.Response.FileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Response.FileInfo other) {
        if (other == protos.Response.FileInfo.getDefaultInstance()) return this;
        internalGetMutablePiecesInfo().mergeFrom(
            other.internalGetPiecesInfo());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Response.FileInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Response.FileInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Long, protos.Response.PeersList> piecesInfo_;
      private com.google.protobuf.MapField<java.lang.Long, protos.Response.PeersList>
      internalGetPiecesInfo() {
        if (piecesInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PiecesInfoDefaultEntryHolder.defaultEntry);
        }
        return piecesInfo_;
      }
      private com.google.protobuf.MapField<java.lang.Long, protos.Response.PeersList>
      internalGetMutablePiecesInfo() {
        onChanged();;
        if (piecesInfo_ == null) {
          piecesInfo_ = com.google.protobuf.MapField.newMapField(
              PiecesInfoDefaultEntryHolder.defaultEntry);
        }
        if (!piecesInfo_.isMutable()) {
          piecesInfo_ = piecesInfo_.copy();
        }
        return piecesInfo_;
      }

      public int getPiecesInfoCount() {
        return internalGetPiecesInfo().getMap().size();
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */

      @java.lang.Override
      public boolean containsPiecesInfo(
          long key) {
        
        return internalGetPiecesInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPiecesInfoMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, protos.Response.PeersList> getPiecesInfo() {
        return getPiecesInfoMap();
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Long, protos.Response.PeersList> getPiecesInfoMap() {
        return internalGetPiecesInfo().getMap();
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */
      @java.lang.Override

      public protos.Response.PeersList getPiecesInfoOrDefault(
          long key,
          protos.Response.PeersList defaultValue) {
        
        java.util.Map<java.lang.Long, protos.Response.PeersList> map =
            internalGetPiecesInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */
      @java.lang.Override

      public protos.Response.PeersList getPiecesInfoOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, protos.Response.PeersList> map =
            internalGetPiecesInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPiecesInfo() {
        internalGetMutablePiecesInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */

      public Builder removePiecesInfo(
          long key) {
        
        internalGetMutablePiecesInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, protos.Response.PeersList>
      getMutablePiecesInfo() {
        return internalGetMutablePiecesInfo().getMutableMap();
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */
      public Builder putPiecesInfo(
          long key,
          protos.Response.PeersList value) {
        
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutablePiecesInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;uint64, .PeersList&gt; piecesInfo = 1;</code>
       */

      public Builder putAllPiecesInfo(
          java.util.Map<java.lang.Long, protos.Response.PeersList> values) {
        internalGetMutablePiecesInfo().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileInfo)
    }

    // @@protoc_insertion_point(class_scope:FileInfo)
    private static final protos.Response.FileInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Response.FileInfo();
    }

    public static protos.Response.FileInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileInfo>
        PARSER = new com.google.protobuf.AbstractParser<FileInfo>() {
      @java.lang.Override
      public FileInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.Response.FileInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PieceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PieceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>uint64 pieceNumber = 2;</code>
     * @return The pieceNumber.
     */
    long getPieceNumber();

    /**
     * <code>bytes piece = 3;</code>
     * @return The piece.
     */
    com.google.protobuf.ByteString getPiece();

    /**
     * <code>bytes pieceHash = 4;</code>
     * @return The pieceHash.
     */
    com.google.protobuf.ByteString getPieceHash();
  }
  /**
   * Protobuf type {@code PieceInfo}
   */
  public static final class PieceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PieceInfo)
      PieceInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PieceInfo.newBuilder() to construct.
    private PieceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PieceInfo() {
      fileName_ = "";
      piece_ = com.google.protobuf.ByteString.EMPTY;
      pieceHash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PieceInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PieceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 16: {

              pieceNumber_ = input.readUInt64();
              break;
            }
            case 26: {

              piece_ = input.readBytes();
              break;
            }
            case 34: {

              pieceHash_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Response.internal_static_PieceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Response.internal_static_PieceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Response.PieceInfo.class, protos.Response.PieceInfo.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIECENUMBER_FIELD_NUMBER = 2;
    private long pieceNumber_;
    /**
     * <code>uint64 pieceNumber = 2;</code>
     * @return The pieceNumber.
     */
    @java.lang.Override
    public long getPieceNumber() {
      return pieceNumber_;
    }

    public static final int PIECE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString piece_;
    /**
     * <code>bytes piece = 3;</code>
     * @return The piece.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPiece() {
      return piece_;
    }

    public static final int PIECEHASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString pieceHash_;
    /**
     * <code>bytes pieceHash = 4;</code>
     * @return The pieceHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPieceHash() {
      return pieceHash_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (pieceNumber_ != 0L) {
        output.writeUInt64(2, pieceNumber_);
      }
      if (!piece_.isEmpty()) {
        output.writeBytes(3, piece_);
      }
      if (!pieceHash_.isEmpty()) {
        output.writeBytes(4, pieceHash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (pieceNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, pieceNumber_);
      }
      if (!piece_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, piece_);
      }
      if (!pieceHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, pieceHash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Response.PieceInfo)) {
        return super.equals(obj);
      }
      protos.Response.PieceInfo other = (protos.Response.PieceInfo) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (getPieceNumber()
          != other.getPieceNumber()) return false;
      if (!getPiece()
          .equals(other.getPiece())) return false;
      if (!getPieceHash()
          .equals(other.getPieceHash())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + PIECENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPieceNumber());
      hash = (37 * hash) + PIECE_FIELD_NUMBER;
      hash = (53 * hash) + getPiece().hashCode();
      hash = (37 * hash) + PIECEHASH_FIELD_NUMBER;
      hash = (53 * hash) + getPieceHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Response.PieceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.PieceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.PieceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.PieceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.PieceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Response.PieceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Response.PieceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Response.PieceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Response.PieceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Response.PieceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Response.PieceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Response.PieceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Response.PieceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PieceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PieceInfo)
        protos.Response.PieceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Response.internal_static_PieceInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Response.internal_static_PieceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Response.PieceInfo.class, protos.Response.PieceInfo.Builder.class);
      }

      // Construct using protos.Response.PieceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileName_ = "";

        pieceNumber_ = 0L;

        piece_ = com.google.protobuf.ByteString.EMPTY;

        pieceHash_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Response.internal_static_PieceInfo_descriptor;
      }

      @java.lang.Override
      public protos.Response.PieceInfo getDefaultInstanceForType() {
        return protos.Response.PieceInfo.getDefaultInstance();
      }

      @java.lang.Override
      public protos.Response.PieceInfo build() {
        protos.Response.PieceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.Response.PieceInfo buildPartial() {
        protos.Response.PieceInfo result = new protos.Response.PieceInfo(this);
        result.fileName_ = fileName_;
        result.pieceNumber_ = pieceNumber_;
        result.piece_ = piece_;
        result.pieceHash_ = pieceHash_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Response.PieceInfo) {
          return mergeFrom((protos.Response.PieceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Response.PieceInfo other) {
        if (other == protos.Response.PieceInfo.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getPieceNumber() != 0L) {
          setPieceNumber(other.getPieceNumber());
        }
        if (other.getPiece() != com.google.protobuf.ByteString.EMPTY) {
          setPiece(other.getPiece());
        }
        if (other.getPieceHash() != com.google.protobuf.ByteString.EMPTY) {
          setPieceHash(other.getPieceHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Response.PieceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Response.PieceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private long pieceNumber_ ;
      /**
       * <code>uint64 pieceNumber = 2;</code>
       * @return The pieceNumber.
       */
      @java.lang.Override
      public long getPieceNumber() {
        return pieceNumber_;
      }
      /**
       * <code>uint64 pieceNumber = 2;</code>
       * @param value The pieceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPieceNumber(long value) {
        
        pieceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 pieceNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPieceNumber() {
        
        pieceNumber_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString piece_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes piece = 3;</code>
       * @return The piece.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPiece() {
        return piece_;
      }
      /**
       * <code>bytes piece = 3;</code>
       * @param value The piece to set.
       * @return This builder for chaining.
       */
      public Builder setPiece(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        piece_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes piece = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPiece() {
        
        piece_ = getDefaultInstance().getPiece();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pieceHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes pieceHash = 4;</code>
       * @return The pieceHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPieceHash() {
        return pieceHash_;
      }
      /**
       * <code>bytes pieceHash = 4;</code>
       * @param value The pieceHash to set.
       * @return This builder for chaining.
       */
      public Builder setPieceHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pieceHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes pieceHash = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPieceHash() {
        
        pieceHash_ = getDefaultInstance().getPieceHash();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PieceInfo)
    }

    // @@protoc_insertion_point(class_scope:PieceInfo)
    private static final protos.Response.PieceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Response.PieceInfo();
    }

    public static protos.Response.PieceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PieceInfo>
        PARSER = new com.google.protobuf.AbstractParser<PieceInfo>() {
      @java.lang.Override
      public PieceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PieceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PieceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PieceInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.Response.PieceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PeersList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PeersList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileInfo_PiecesInfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileInfo_PiecesInfoEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PieceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PieceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protos/response.proto\032\021protos/node.pro" +
      "to\"(\n\tPeersList\022\033\n\005nodes\030\001 \003(\0132\014.NodeDet" +
      "ails\"x\n\010FileInfo\022-\n\npiecesInfo\030\001 \003(\0132\031.F" +
      "ileInfo.PiecesInfoEntry\032=\n\017PiecesInfoEnt" +
      "ry\022\013\n\003key\030\001 \001(\004\022\031\n\005value\030\002 \001(\0132\n.PeersLi" +
      "st:\0028\001\"T\n\tPieceInfo\022\020\n\010fileName\030\001 \001(\t\022\023\n" +
      "\013pieceNumber\030\002 \001(\004\022\r\n\005piece\030\003 \001(\014\022\021\n\tpie" +
      "ceHash\030\004 \001(\014B\022\n\006protosB\010Responseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protos.Node.getDescriptor(),
        });
    internal_static_PeersList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PeersList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PeersList_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileInfo_descriptor,
        new java.lang.String[] { "PiecesInfo", });
    internal_static_FileInfo_PiecesInfoEntry_descriptor =
      internal_static_FileInfo_descriptor.getNestedTypes().get(0);
    internal_static_FileInfo_PiecesInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileInfo_PiecesInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PieceInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PieceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PieceInfo_descriptor,
        new java.lang.String[] { "FileName", "PieceNumber", "Piece", "PieceHash", });
    protos.Node.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
